unify put mnemonic; always value first
AluVM/rust-aluvm pull request #77
Opened 2023-06-12 14:31 UTC by 6293

Closes https://github.com/AluVM/rust-aluvm/issues/75

2023-06-12 16:45 UTC, 6293 commented on src/reg/core_regs.rs
> +                write!(f, "{}s16{}[{}{:02}{}]={}{}{}h\n\t", reg, eq, reset, i, eq, val, v, reset)?;
what is trailing `h` on every register?

```
A-REG:  a16[01]=0001h   a16[02]=0002h   
                
F-REG:  
R-REG:  r8192[01]=1h
                
S-REG:  s16[01]="aaa"h
        s16[02]="aaa"h
```

2023-06-12 17:31 UTC, 6293 commented on src/reg/core_regs.rs
> +        }
```
put   100,r8192[1];
put   2,r8192[2];
put   18,a16[1];
put   2,a16[2];
put   "aaa",s16[1];
put   "aaa",s16[2];
```

would be displayed as

```
CTRL:   st0=true cy0=0 ca0=8 cl0=~ cp0=0 
                cs0=0 @ alien_vista_plaza_11111111111111111111111111111111
                   
A-REG:  a16[01]=0012h   a16[02]=0002h   
                
F-REG:  
R-REG:  r8192[01]=64h
                
S-REG:  s16[01]="aaa"
        s16[02]="aaa"
```

2023-06-14 07:58 UTC, dr-orlovsky reviewed
I propose to make the PR not-API breaking (see my comment).

Also, what do you think, should we use left-to-right argument order (like now, with value going first), or do a X86-assembly way where the destination goes first?

2023-06-14 09:07 UTC, 6293 commented
> Also, what do you think, should we use left-to-right argument order (like now, with value going first), or do a X86-assembly way where the destination goes first?

We have both styles for now (mov accepts dest first while extr). So we can align to the major X86 style

2023-06-14 10:08 UTC, dr-orlovsky commented
It can be that Intel style BTW is not the best one so we might want to stick to more natural (for english) left-to-right order: https://stackoverflow.com/questions/67597388/correct-order-of-source-and-destination-in-assembly-language

2023-06-14 10:28 UTC, dr-orlovsky requested changes
LGTM except that we still need not to change `BytesOp` variants - otherwise we would break bytecode compatibility (and would also need a major version release).

So yes, the enum variants will not match the mnemonic representation. Sad, but otherwise too breaking downstream.

2023-06-14 10:34 UTC, 6293 commented
> LGTM except that we still need not to change BytesOp variants - otherwise we would break bytecode compatibility (and would also need a major version release).

the change on BytesOp::Put has been reverted

2023-06-14 10:49 UTC, dr-orlovsky approved these changes
ACK 6cae121c54e1a2590f7edb933b965b7ee4931f67

2023-06-14 10:49 UTC, merged

2023-06-14 10:50 UTC, dr-orlovsky commented
Thank you very much, great work!